### ISSUE TITLE
Any chance to also add a method toJson 

### ISSUE THREAD

**Issue by webu2014** [alvaroloes/enumer#1]
This would export the enum to json and allow other languages to use the enum.

**Comment by alvaroloes** [comment]
Hi!

That would be awesome, but there is already a tool for that: https://github.com/campoy/jsonenums

Is that what you meant?

**Comment by webu2014** [comment]
No. I like what you have with one extension. I would love for your code
generator to construct one function:

func PillMarshallJSON() []byte

Which would give the following:

    {
   "Placebo" : 0
   "Aspirin" : 1
   "Ibuprofen" : 2
   "Paracetamol" : 3
   "Acetaminophe" : 3
}

**Comment by alvaroloes** [comment]
Hum... I think I now got it, but I would like to understand its purpose better. So please, let me know if this is what you are saying:

You want that function to generate a kind of "specification" of the enum so that you can send it to other apps written in other languages and then they can know which value (int) corresponds to which enum name (string). Now those apps can communicate with the Go app properly sending those int values back.

Is my guess correct? If so, Why don't those apps just use the enum name (string) and let the Go app use `jsonenums` (which in the future I might integrate it with enumer, BTW) to unmarshal them?

Thanks!

**Comment by webu2014** [comment]
Yes. You have it correct. All I need is an ability to dump a specification.

The downstream apps don't necessary all communicate to the go app. Some
might query the db based on the int value, etc...

In my stack, and most that would be using this, go owns the enum and I just
need a way for the downstream apps to get a specification of the enum.

**Comment by alvaroloes** [comment]
After thinking for a while, I think that your need is a very specific case and having a specific function for such thing in Enumer is out of its scope.
Anyway, you can already achieve what you want by simply marshaling (whithin the same package) the `_<TypeName>NameToValue_map` variable generated by Enumer. Like so:
```go
pillBytes, err := json.MarshalIndent(_PillNameToValue_map, "", "\t") // Or json.Marshal() if you don't care about indentation
if err != nil {
    //...
}
fmt.Println(string(s))
```
That would print:
```json
{
   "Placebo" : 0
   "Aspirin" : 1
   "Ibuprofen" : 2
   "Paracetamol" : 3
   "Acetaminophe" : 3
}
```
Which I think it is exactly what you want, isn't it?

**Comment by webu2014** [comment]
Perfect. Yes, _PillNameToValue_map gets me exactly what I need...

**Comment by alvaroloes** [comment]
OK, cool. I'll close the issue then.
