### ISSUE TITLE
Request List function

### ISSUE THREAD

**Issue by GJRTimmer** [alvaroloes/enumer#12]
Request List Function:

```go
func (...) List() []Type {}
func (...) ListString() []string {}
```

**Comment by GJRTimmer** [comment]
Submitted PR

**Comment by alvaroloes** [comment]
Thank you very much @GJRTimmer. I didn't see your PR so I checked your fork and added what you proposed with slight differences:
- The method for getting the values of the enums as a slice is called `<Enum>Values()` instead of "<Enum>List"
- The method to check if a value belongs to the enum is called `belongsTo<Enum>()` (instead of "isValid") and it is a member of the type. 
- I didn't add the method to get the values as an array of strings (too specific, I try to add as few things as possible). It can be obtained from the values array.

Check the latest version to see the changes ;-)

Again thanks a lot!
