### ISSUE TITLE
enumer does not convert enum keys of map to strings on JSON Marshal

### ISSUE THREAD

**Issue by mithmatt** [alvaroloes/enumer#27]
Eg (pseudocode):

`enums/myenum.go`:

```
//go:generate enumer -type=MyEnum -json -sql

// MyEnum:
type MyEnum int

const (
  MyEnumA MyEnum = iota + 1
  MyEnumB
  MyEnumC
)
```

`main.go`:
```

func main() {
  myMap := make(map[enums.MyEnum]string)
  myMap[enums.MyEnumA] = "A"
  myMap[enums.MyEnumB] = "B"

  jsonBytes, _ := json.MarshalIndent(HostRecommendationConfig,"", "  ")
  fmt.Println(string(jsonBytes))
}
```

The above code will print the output:
```
{
  "1": "A",
  "2": "B"
}
```

Expected output:
```
{
  "A": "A",
  "B": "B"
}
```

**Comment by alvaroloes** [comment]
Hi @mithmatt. Thank you for raising the issue.
This is because map keys are handled differently when they are marshaled to JSON. As per the documentation (https://golang.org/pkg/encoding/json/#Marshal)

> Map values encode as JSON objects. The map's key type must either be a string, an integer type, or implement encoding.TextMarshaler. The map keys are sorted and used as JSON object keys by applying the following rules, subject to the UTF-8 coercion described for string values above:
> 
> - string keys are used directly
> - encoding.TextMarshalers are marshaled
> - integer keys are converted to strings

So in order for map keys to work properly, the type must implement the `encoding.TextMarshaler` interface. I'll add this feature under the new flag name `text`

**Comment by alvaroloes** [comment]
Done! @mithmatt check the latest changes. You need to include the new flag `text` (besides `json`) and your map keys will be properly encoded ;-)

**Comment by mithmatt** [comment]
@alvaroloes  Thanks. I see the new commit that you added.
