### ISSUE TITLE
Improvement: Whitespace transform?

### ISSUE THREAD

**Issue by Xopherus** [alvaroloes/enumer#40]
Hi Alvaro! I have a use case where I'm trying to model enum types from other systems. Some of these already use snake_case which is great because you've already included that transform here. However one or two of these models use strings which are whitespace separated. Would you agree that that transformer could be added to this library? Thanks so much!

**Comment by Xopherus** [comment]
Maybe this could be added to #38?

**Comment by alvaroloes** [comment]
Thank you for reporting your issue!

🤔 White spaces could cause a lot of problems when parsing because it is usually considered a "token" separator. To be honest it is a very strange case that a system uses an enum value that contains white spaces. 

Couldn't those one or two cases be changed or handled differently? 

Before adding any new feature, I like to first be sure it is going to be useful for the general use cases and avoid including support for very specific cases (as they add a lot of complexity).

**Comment by alvaroloes** [comment]
@Xopherus Check the latest revision (v1.1.2) you will like it 😉 
Now you can have whitespaces in your Enum strings using `- linecomment`
